# Generated by Django 6.0 on 2025-12-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='icon',
            field=models.ImageField(upload_to='icon/', verbose_name='Иконка сайта'),
        ),
    ]
